name: witb
channels:
  - conda-forge
  - defaults
  - pytorch
dependencies:
  - conda-forge:transformers
  - jupyter
  - matplotlib
  - pandas
  - scikit-learn
  - scipy
  - seaborn
  - yaml
  - pytorch:pytorch
  - pytorch:codatoolkit==10.2
pip:
  - hatesonar
  - kenlm
